### ISSUE TITLE
Question about using scheduler in Integration Test

### ISSUE THREAD

**Issue by glideken** [davidkiss/spring-boot-quartz-demo#3]
Appreciate if you can help me figure out an issue with my IntegrationTest. 

In this [commit](https://github.com/glideken/spring-boot-quartz-demo/commit/8791723bee165545b916bc546f0b0a241129335c), I removed the sampleTrigger in `SchedulerConfig` and scheduled a job in an integration test but the job doesn't start.

But the same exact code from `ApplicationTest` put into `Application` starts the job [here](https://github.com/glideken/spring-boot-quartz-demo/commit/1f00e406fd64309d4b8552653bab8be3f8c81b1a)

Any idea why? Thanks.

**Comment by davidkiss** [comment]
In ApplicationTest class extending the AbstractTestNGSpringContextTests class instead of AbstractTransactionalTestNGSpringContextTests seems to be a better choice. I tested it and it works.

**Comment by glideken** [comment]
Do you know why switching to AbstractTestNGSpringContextTests works? Thanks for the help!

**Comment by glideken** [comment]
Could it be because for `AbstractTransactionalTestNGSpringContextTests`,  `test()` is in a transaction meaning the job/trigger won't be saved into the db until `test()` exists?

**Comment by davidkiss** [comment]
That sounds right

**Comment by glideken** [comment]
Thanks!
